# Generated by Django 4.2.2 on 2023-06-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_remove_chapter_content_remove_chapter_created_at_and_more'),
        ('lectures', '0003_remove_lecture_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lecture',
            name='chapter',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='chapters.chapter'),
            preserve_default=False,
        ),
    ]
