# Generated by Django 4.2.2 on 2023-06-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_remove_chapter_content_remove_chapter_created_at_and_more'),
        ('lectures', '0004_remove_lecture_created_at_remove_lecture_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chapters.chapter'),
        ),
    ]
